kiplot:
  version: 1

preflight:
  ignore_unconnected: false
        
outputs:
  - name: 'print schema'
    comment: "Print schematic (PDF)"
    type: pdf_sch_print

  - name: 'print schema'
    comment: "Print schematic (SVG)"
    type: svg_sch_print
