name: test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  schematics:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: kicad-exports schematics
      uses: nerdyscout/kicad-exports@develop
      with:
        config: schematics.kiplot.yaml
        dir: test
        board: test/test.kicad_pcb
        schema: test/test.sch
    - name: "check output: schematics"
      uses: andstor/file-existence-action@v1
      with:
        files: "test/docs/*.svg, test/docs/*.pdf"
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: docs
        path: test/docs/*

  bom:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: kicad-exports bom
      uses: nerdyscout/kicad-exports@develop
      with:
        config: bom.kiplot.yaml
        dir: test
        board: test/test.kicad_pcb
        schema: test/test.sch
    - name: "check output: bom"
      if: success()
      uses: andstor/file-existence-action@v1
      with:
        files: "test/docs/bom/*.html, test/docs/bom/*.csv, test/docs/bom/*.xlsx"
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: bom
        path: test/docs/bom/*

  fabrications:
    runs-on: ubuntu-latest
    # continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - name: kicad-exports fabrications 
      uses: nerdyscout/kicad-exports@develop
      with:
        config: fabrications.kiplot.yaml
        dir: test
        board: test/test.kicad_pcb
        schema: test/test.sch
    - name: "check output: kiplot-position"
      uses: andstor/file-existence-action@v1
      with:
        files: "test/gerber/*both-pos.csv"
    - name: "check output: kiplot-drills"
      uses: andstor/file-existence-action@v1
      with:
        files: "test/gerber/test-PTH.drl, test/gerber/test-NPTH.drl"
    - uses: andstor/file-existence-action@v1
      with:
        files: "test/gerber/test-PTH-drl.gbr, test/gerber/test-NPTH-drl.gbr"
    - name: "check output: kiplot-gerber"
      uses: andstor/file-existence-action@v1
      with:
        files: "test/gerber/test-Edge_Cuts.gbr, test/gerber/test-F_Cu.gbr, test/gerber/test-B_SilkS.gbr"
    - uses: actions/upload-artifact@v2
      with:
        name: gerber
        path: test/gerber/*

#  plot:
#    runs-on: ubuntu-latest
#    continue-on-error: true
#    steps:
#    - uses: actions/checkout@v2
#    - name: kicad-exports tracespace-board
#      uses: nerdyscout/kicad-exports@develop
#      with:
#        config: tracespace-board.kiplot.yaml
#        dir: test
#        schema: test/test.sch
#        board: test/test.kicad_pcb
#    - name: "check output: tracespace-board"
#      uses: andstor/file-existence-action@v1
#      with:
#        files: "test/docs/img/test_Board_Top.svg, test/docs/img/test_Board_Bottom.svg"
#
#    - name: kicad-exports tracespace-assembly
#      uses: nerdyscout/kicad-exports@develop
#      with:
#        config: test/tracespace-assembly.kiplot.yaml
#        dir: test
#        schema: test/test.sch
#        board: test/test.kicad_pcb
#    - name: "check output: tracespace-assembly"
#      uses: andstor/file-existence-action@v1
#      with:
#        files: "test/docs/img/test_Assembly_Top.svg, test/docs/img/test_Assembly_Bottom.svg"
#
#    - uses: actions/upload-artifact@v2
#      with:
#        name: images
#        path: test/docs/img/*
